CREATE DATABASE QuanLySinhVien
GO
USE QuanLySinhVien

CREATE TABLE LOP(
MALOP VARCHAR(10) PRIMARY KEY,
TENLOP NVARCHAR(50),
GVCN NVARCHAR(30))

CREATE TABLE SINHVIEN(
MASV VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50),
NGAYSINH DATE, 
GIOITINH BIT,
QUEQUAN NVARCHAR(100),
MALOP VARCHAR(10))

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

INSERT INTO LOP(MALOP, TENLOP, GVCN) VALUES
('CDNK7CNTTA', N'CĐN K7 Công Nghệ Thông Tin A', N'Nguyễn Thành Phú'),
('CDNK7CNTTB', N'CĐN K7 Công Nghệ Thông Tin B', N'Phan Minh Huyền'),
('CDNK9CNTT', N'CĐN K9 Công Nghệ Thông Tin', N'Đào Thanh Mây');

INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, GIOITINH, QUEQUAN, MALOP) VALUES
('C07-532', N'Võ Thị Trúc Trâm', '1991-04-14', 0, N'Quy Nhơn, Bình Định', 'CDNK7CNTTA'),
('C07-535', N'Nguyễn Hữu Trung', '1991-04-14', 1, N'Quy Nhơn, Bình Định', 'CDNK7CNTTA'),
('C07-536', N'Nguyễn Thanh Tuấn', '1991-12-15', 1, N'Tây Sơn, Bình Định', 'CDNK7CNTTA');

INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, GIOITINH, QUEQUAN, MALOP) VALUES
('C07-539', N'Trần Thị Tường Vi', '1991-05-12', 0, N'Tây Sơn, Bình Định', 'CDNK7CNTTB'),
('C07-541', N'Đặng Cao Bảo Anh', '1991-01-15', 1, N'Tây Sơn, Bình Định', 'CDNK7CNTTB'),
('C07-549', N'Đinh Công Tuyết Hanh', '1991-05-15', 0, N'Tây Sơn, Bình Định', 'CDNK7CNTTB'),
('C07-550', N'Lê Đặng Minh Hậu', '1991-05-25', 1, N'Tây Sơn, Bình Định', 'CDNK7CNTTB');

INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, GIOITINH, QUEQUAN, MALOP) VALUES
('C09-558', N'Nguyễn Kiên Khang', '1991-09-16', 1, N'Quy Nhơn, Bình Định', 'CDNK9CNTT'),
('C09-559', N'Trần Văn Khôi', '1991-05-16', 1, N'Quy Nhơn, Bình Định', 'CDNK9CNTT'),
('C09-560', N'Nguyễn Quốc Khương', '1991-07-25', 1, N'Phù Cát, Bình Định', 'CDNK9CNTT');

SELECT SINHVIEN.MASV, SINHVIEN.MALOP, LOP.MALOP, SINHVIEN.HOTEN FROM SINHVIEN, LOP 
WHERE SINHVIEN.MALOP = LOP.MALOP AND LOP.TENLOP = N'CĐN K7 Công Nghệ Thông Tin A'

SELECT MASV, HOTEN, NGAYSINH, GIOITINH, SINHVIEN.MALOP FROM SINHVIEN, LOP
WHERE SINHVIEN.MALOP = LOP.MALOP AND LOP.TENLOP = N'CĐN K7 Công Nghệ Thông Tin A' 

INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, GIOITINH, QUEQUAN, MALOP) VALUES
('C07-569', N'Trần Vũ Cát Tường', '1991/11/12', 0, N'Tây Sơn, Bình Định', 'CDNK7CNTTB')